const questions = [
  {
    id: 1,
    question: "What is the largest mountain?",
    answer: "Mount Everest",
    category: "geo",
    fact: "Mount Everest stands at 8,848.86 meters (29,031.7 feet) above sea level, making it the highest point on Earth.",
  },
  {
    id: 56,
    question: "Who invented the periodic table?",
    answer: "Dmitri Mendeleev",
    category: "people",
    fact: "In 1869, Dmitri Mendeleev created the first version of the periodic table, organizing the elements by their atomic weight and properties.",
  },
  {
    id: 57,
    question: "Who invented the modern refrigerator?",
    answer: "Carl von Linde",
    category: "people",
    fact: "Carl von Linde, a German engineer, developed the first reliable and efficient refrigerator in 1876, using a method of liquefying gases.",
  },
  {
    id: 58,
    question: "Who is known as the 'father of genetics'?",
    answer: "Gregor Mendel",
    category: "people",
    fact: "Gregor Mendel's experiments with pea plants in the 19th century laid the foundation for the science of genetics, introducing the concept of inherited traits.",
  },
  {
    id: 59,
    question: "Who invented the typewriter?",
    answer: "Christopher Latham Sholes",
    category: "people",
    fact: "Christopher Latham Sholes invented the first practical typewriter in 1868, also creating the QWERTY keyboard layout still in use today.",
  },
  {
    id: 60,
    question: "Who developed the first programmable loom?",
    answer: "Joseph Marie Jacquard",
    category: "people",
    fact: "In 1804, Joseph Marie Jacquard invented a loom controlled by punch cards, which became a precursor to modern computer programming.",
  },

  {
    id: 2,
    question: "Which is the longest river in the world?",
    answer: "The Nile",
    category: "geo",
    fact: "The Nile River is about 6,650 km (4,130 miles) long and flows through 11 countries in northeastern Africa.",
  },
  {
    id: 3,
    question: "Which desert is the largest in the world?",
    answer: "The Antarctic Desert",
    category: "geo",
    fact: "The Antarctic Desert is around 14 million square kilometers (5.4 million square miles), making it the largest desert on Earth.",
  },
  {
    id: 4,
    question: "What is the smallest country in the world?",
    answer: "Vatican City",
    category: "geo",
    fact: "Vatican City is an independent city-state that covers just 44 hectares (110 acres) and has a population of about 800 people.",
  },
  {
    id: 5,
    question: "Which country has the most time zones?",
    answer: "France",
    category: "geo",
    fact: "Due to its overseas territories, France spans 12 time zones, more than any other country.",
  },

  {
    id: 6,
    question: "What is the deepest ocean trench?",
    answer: "The Mariana Trench",
    category: "geo",
    fact: "The Mariana Trench is located in the western Pacific Ocean and reaches a depth of approximately 10,994 meters (36,070 feet).",
  },

  {
    id: 18,
    question: "What is the hottest desert in the world?",
    answer: "The Sahara Desert",
    category: "geo",
    fact: "The Sahara Desert, in northern Africa, regularly experiences temperatures above 50°C (122°F) in summer.",
  },
  {
    id: 19,
    question: "Which country has the most volcanoes?",
    answer: "Indonesia",
    category: "geo",
    fact: "Indonesia has around 130 active volcanoes due to its location on the Pacific Ring of Fire.",
  },

  {
    id: 101,
    question: "Which artist is known for cutting off part of his own ear?",
    answer: "Vincent van Gogh",
    category: "arts",
    fact: "Vincent van Gogh is a post-impressionist painter known for his expressive use of color and emotional depth, but he struggled with mental illness throughout his life.",
  },
  {
    id: 102,
    question: "Who painted the ceiling of the Sistine Chapel?",
    answer: "Michelangelo",
    category: "arts",
    fact: "Michelangelo spent four years painting the Sistine Chapel ceiling, a masterpiece of Renaissance art that features scenes from the Book of Genesis.",
  },
  {
    id: 171,
    question: "What is the largest land animal?",
    answer: "African Elephant",
    category: "wild",
    fact: "The African elephant can weigh up to 12,000 pounds and is known for its large ears and tusks.",
  },
  {
    id: 172,
    question: "Which animal is known as the king of the jungle?",
    answer: "Lion",
    category: "wild",
    fact: "Lions are known for their strength and majestic manes, and they live in social groups called prides.",
  },
  {
    id: 173,
    question: "What is the fastest land animal?",
    answer: "Cheetah",
    category: "wild",
    fact: "Cheetahs can run up to 70 miles per hour, making them the fastest animals on land for short distances.",
  },
  {
    id: 174,
    question: "What is the largest species of bird?",
    answer: "Ostrich",
    category: "wild",
    fact: "Ostriches can grow up to 9 feet tall and are flightless, but they can run at speeds up to 40 miles per hour.",
  },
  {
    id: 175,
    question: "Which animal has the longest lifespan in the wild?",
    answer: "Bowhead Whale",
    category: "wild",
    fact: "Bowhead whales can live for over 200 years, making them one of the longest-living mammals on Earth.",
  },
  {
    id: 103,
    question: "What art movement is Pablo Picasso associated with?",
    answer: "Cubism",
    category: "arts",
    fact: "Pablo Picasso co-founded Cubism, an art movement that broke objects down into geometric shapes, changing the perspective on how art could represent reality.",
  },
  {
    id: 104,
    question: "Which artist is famous for the painting 'The Starry Night'?",
    answer: "Vincent van Gogh",
    category: "arts",
    fact: "'The Starry Night' was painted in 1889 while Van Gogh was in a mental asylum in Saint-Rémy-de-Provence, and it depicts a swirling night sky over a small town.",
  },

  {
    id: 121,
    question: "Who is known as the 'King of Pop'?",
    answer: "Michael Jackson",
    category: "music",
    fact: "Michael Jackson revolutionized the music industry with his groundbreaking albums and iconic performances, becoming one of the most influential musicians of all time.",
  },
  {
    id: 122,
    question: "Which band released the album 'The Dark Side of the Moon'?",
    answer: "Pink Floyd",
    category: "music",
    fact: "Released in 1973, 'The Dark Side of the Moon' is one of the best-selling albums of all time, known for its innovative production and philosophical lyrics.",
  },
  {
    id: 123,
    question: "Who is the lead singer of the rock band U2?",
    answer: "Bono",
    category: "music",
    fact: "Bono, whose real name is Paul David Hewson, is the lead vocalist of U2, a band known for its activism and musical influence since the 1980s.",
  },
  {
    id: 124,
    question: "Which composer wrote the 'Fifth Symphony'?",
    answer: "Ludwig van Beethoven",
    category: "music",
    fact: "Beethoven’s 'Fifth Symphony' is one of the most famous classical compositions, known for its distinctive four-note opening motif.",
  },
  {
    id: 125,
    question: "Who is the best-selling female recording artist of all time?",
    answer: "Madonna",
    category: "music",
    fact: "With over 300 million records sold worldwide, Madonna is recognized as the best-selling female recording artist and a major pop culture icon.",
  },
  {
    id: 105,
    question: "Who sculpted 'David'?",
    answer: "Michelangelo",
    category: "arts",
    fact: "Michelangelo's 'David' is one of the most iconic sculptures of the Renaissance, showcasing the biblical hero at the moment before his battle with Goliath.",
  },
  {
    id: 20,
    question: "What is the coldest inhabited place on Earth?",
    answer: "Oymyakon, Russia",
    category: "geo",
    fact: "Oymyakon has recorded temperatures as low as -67.7°C (-89.9°F) and is considered the coldest inhabited place on Earth.",
  },
  {
    id: 21,
    question: "Which is the flattest continent?",
    answer: "Australia",
    category: "geo",
    fact: "Australia is the flattest and, after Antarctica, the driest continent.",
  },
  {
    id: 22,
    question: "Which country has the highest number of lakes?",
    answer: "Canada",
    category: "geo",
    fact: "Canada is home to around 60% of the world’s lakes, with over 2 million lakes.",
  },
  {
    id: 23,
    question: "Which country is known as the Land of a Thousand Lakes?",
    answer: "Finland",
    category: "geo",
    fact: "Finland has about 188,000 lakes, earning it the nickname ‘The Land of a Thousand Lakes.’",
  },
  {
    id: 7,
    question: "Which continent has the most countries?",
    answer: "Africa",
    category: "geo",
    fact: "Africa is home to 54 recognized sovereign nations, the most of any continent.",
  },
  {
    id: 141,
    question: "What is the largest planet in our solar system?",
    answer: "Jupiter",
    category: "astro",
    fact: "Jupiter is so large that it could fit all the other planets inside it and still have room left over.",
  },
  {
    id: 142,
    question: "What is the name of the galaxy we live in?",
    answer: "The Milky Way",
    category: "astro",
    fact: "The Milky Way is a barred spiral galaxy, and it's estimated to contain over 100 billion stars.",
  },
  {
    id: 143,
    question: "What is the closest star to Earth?",
    answer: "The Sun",
    category: "astro",
    fact: "The Sun is about 93 million miles away from Earth and provides the energy that supports life on our planet.",
  },
  {
    id: 144,
    question: "What is the name of the first satellite sent into space?",
    answer: "Sputnik 1",
    category: "astro",
    fact: "Launched by the Soviet Union in 1957, Sputnik 1 was the first artificial satellite to orbit the Earth.",
  },
  {
    id: 176,
    question: "What is the tallest animal in the world?",
    answer: "Giraffe",
    category: "wild",
    fact: "Giraffes can grow up to 18 feet tall, and their long necks allow them to feed on leaves high up in trees.",
  },
  {
    id: 177,
    question: "Which bird is known for its colorful tail feathers?",
    answer: "Peacock",
    category: "wild",
    fact: "Male peacocks display their large, colorful tail feathers to attract mates, making them one of the most eye-catching birds.",
  },
  {
    id: 178,
    question:
      "Which animal is known for its ability to change colors to blend into its surroundings?",
    answer: "Chameleon",
    category: "wild",
    fact: "Chameleons can change the color of their skin to match their environment, a feature that helps them hide from predators.",
  },
  {
    id: 179,
    question: "What is the largest species of shark?",
    answer: "Whale Shark",
    category: "wild",
    fact: "Whale sharks can grow over 40 feet long and are filter feeders, meaning they eat plankton and small fish rather than hunting large prey.",
  },
  {
    id: 180,
    question: "What is the only mammal capable of true flight?",
    answer: "Bat",
    category: "wild",
    fact: "Bats are the only mammals that can fly, and some species can fly as fast as 60 miles per hour.",
  },
  {
    id: 181,
    question: "Which animal is the largest carnivore on land?",
    answer: "Polar Bear",
    category: "wild",
    fact: "Polar bears are the largest land carnivores, weighing up to 1,500 pounds, and they rely on sea ice to hunt seals.",
  },
  {
    id: 182,
    question: "What is the fastest bird in flight?",
    answer: "Peregrine Falcon",
    category: "wild",
    fact: "The peregrine falcon can dive at speeds of over 200 miles per hour, making it the fastest bird in the world.",
  },
  {
    id: 183,
    question: "Which animal is known for having a pouch to carry its young?",
    answer: "Kangaroo",
    category: "wild",
    fact: "Kangaroos are marsupials, meaning they have a pouch in which they carry and nurse their young after birth.",
  },
  {
    id: 184,
    question: "Which is the largest reptile in the world?",
    answer: "Saltwater Crocodile",
    category: "wild",
    fact: "Saltwater crocodiles can grow up to 23 feet in length and are found in coastal areas across Southeast Asia and Australia.",
  },
  {
    id: 185,
    question: "Which bird has the largest wingspan?",
    answer: "Wandering Albatross",
    category: "wild",
    fact: "The wandering albatross has a wingspan of up to 11 feet, allowing it to glide over the ocean for long distances with minimal effort.",
  },
  {
    id: 186,
    question: "What is the smallest mammal in the world?",
    answer: "Bumblebee Bat",
    category: "wild",
    fact: "The bumblebee bat weighs less than a penny and is about the size of a large bumblebee, making it the smallest mammal by size.",
  },
  {
    id: 187,
    question: "Which species of penguin is the largest?",
    answer: "Emperor Penguin",
    category: "wild",
    fact: "The emperor penguin can reach heights of up to 4 feet and is the only penguin species that breeds during the Antarctic winter.",
  },
  {
    id: 188,
    question: "Which animal has the strongest bite force?",
    answer: "Nile Crocodile",
    category: "wild",
    fact: "The Nile crocodile has one of the strongest bite forces in the animal kingdom, capable of crushing bones with ease.",
  },
  {
    id: 189,
    question: "What is the longest venomous snake in the world?",
    answer: "King Cobra",
    category: "wild",
    fact: "The king cobra can grow up to 18 feet long and is the longest venomous snake, found primarily in forests across Southeast Asia.",
  },
  {
    id: 190,
    question: "Which animal is known for its incredible memory?",
    answer: "Elephant",
    category: "wild",
    fact: "Elephants have large brains and are known to have exceptional memories, which help them survive in the wild by remembering migration routes and water sources.",
  },
  {
    id: 145,
    question: "What is the smallest planet in our solar system?",
    answer: "Mercury",
    category: "astro",
    fact: "Mercury is not only the smallest planet but also the closest to the Sun, completing a full orbit in just 88 Earth days.",
  },
  {
    id: 8,
    question: "Which country has the longest coastline?",
    answer: "Canada",
    category: "geo",
    fact: "Canada’s coastline stretches over 202,080 km (125,567 miles), more than any other country in the world.",
  },
  {
    id: 9,
    question: "What is the smallest ocean in the world?",
    answer: "The Arctic Ocean",
    category: "geo",
    fact: "The Arctic Ocean covers about 14 million square kilometers (5.4 million square miles), making it the smallest of the world's five oceans.",
  },
  {
    id: 10,
    question: "Which is the largest island in the world?",
    answer: "Greenland",
    category: "geo",
    fact: "Greenland covers an area of 2,166,086 square kilometers (836,331 square miles), making it the largest island in the world that is not a continent.",
  },
  {
    id: 11,
    question: "Which is the highest waterfall in the world?",
    answer: "Angel Falls",
    category: "geo",
    fact: "Angel Falls, located in Venezuela, has a total height of 979 meters (3,212 feet), making it the world's tallest uninterrupted waterfall.",
  },
  {
    id: 12,
    question: "Which city is located on two continents?",
    answer: "Istanbul",
    category: "geo",
    fact: "Istanbul, Turkey, spans both Europe and Asia, divided by the Bosporus Strait.",
  },
  {
    id: 13,
    question: "What is the largest lake in the world by surface area?",
    answer: "The Caspian Sea",
    category: "geo",
    fact: "The Caspian Sea is a saltwater lake with a surface area of about 371,000 square kilometers (143,000 square miles).",
  },
  {
    id: 14,
    question: "Which country is known as the Land of the Rising Sun?",
    answer: "Japan",
    category: "geo",
    fact: "Japan earned this nickname due to its eastern position in relation to Asia, where the sun rises first.",
  },
  {
    id: 15,
    question: "Which river flows through the most countries?",
    answer: "The Danube River",
    category: "geo",
    fact: "The Danube flows through 10 countries in Central and Eastern Europe, including Germany, Austria, and Romania.",
  },
  {
    id: 16,
    question: "Which continent is the driest?",
    answer: "Antarctica",
    category: "geo",
    fact: "Despite its ice, Antarctica is classified as the driest continent due to extremely low precipitation.",
  },
  {
    id: 17,
    question: "What is the most populated city in the world?",
    answer: "Tokyo",
    category: "geo",
    fact: "As of 2021, Tokyo, Japan, had a population of around 37 million people, making it the most populous urban area.",
  },
  {
    id: 24,
    question: "What is the highest capital city in the world?",
    answer: "La Paz",
    category: "geo",
    fact: "La Paz, Bolivia, sits at about 3,650 meters (11,975 feet) above sea level, making it the highest capital city.",
  },
  {
    id: 25,
    question: "Which is the most mountainous country in Europe?",
    answer: "Switzerland",
    category: "geo",
    fact: "Switzerland is known for its Alps, with about 60% of its land being mountainous.",
  },

  {
    id: 26,
    question: "Which ocean is the warmest?",
    answer: "The Indian Ocean",
    category: "geo",
    fact: "The Indian Ocean is the warmest ocean in the world, with an average temperature of about 22°C (71.6°F).",
  },
  {
    id: 146,
    question: "What is the name of the first human to travel into space?",
    answer: "Yuri Gagarin",
    category: "astro",
    fact: "Yuri Gagarin, a Soviet cosmonaut, orbited the Earth in 1961 aboard Vostok 1, making history as the first human in space.",
  },
  {
    id: 147,
    question: "What is the term for a star that has exploded?",
    answer: "Supernova",
    category: "astro",
    fact: "A supernova is a massive explosion that occurs when a star reaches the end of its life cycle, resulting in a burst of energy and light.",
  },
  {
    id: 148,
    question: "What is the closest planet to Earth?",
    answer: "Venus",
    category: "astro",
    fact: "Venus is often referred to as Earth's 'sister planet' due to its similar size, though its surface conditions are extremely harsh.",
  },
  {
    id: 149,
    question: "Which planet is known for its rings?",
    answer: "Saturn",
    category: "astro",
    fact: "Saturn's rings are made up of ice and rock particles, and they are the most extensive and complex ring system in the solar system.",
  },
  {
    id: 150,
    question: "What do we call a moon that orbits a planet?",
    answer: "A satellite",
    category: "astro",
    fact: "A natural satellite, like our Moon, orbits a planet, while artificial satellites are man-made objects placed in orbit.",
  },
  {
    id: 151,
    question: "What is the name of the second human to walk on the moon?",
    answer: "Buzz Aldrin",
    category: "astro",
    fact: "Buzz Aldrin followed Neil Armstrong during the Apollo 11 mission in 1969, making him the second human to set foot on the Moon.",
  },
  {
    id: 152,
    question: "What is a light-year a measure of?",
    answer: "Distance",
    category: "astro",
    fact: "A light-year is the distance that light travels in one year, approximately 5.88 trillion miles (9.46 trillion kilometers).",
  },
  {
    id: 153,
    question: "Which planet is known as the 'Red Planet'?",
    answer: "Mars",
    category: "astro",
    fact: "Mars gets its red color from iron oxide, or rust, on its surface and is one of the most studied planets in the solar system.",
  },
  {
    id: 154,
    question:
      "What is the name of the first American astronaut to orbit Earth?",
    answer: "John Glenn",
    category: "astro",
    fact: "John Glenn orbited Earth aboard Friendship 7 in 1962, becoming the first American to complete this feat.",
  },
  {
    id: 155,
    question: "What is the name of the largest moon of Saturn?",
    answer: "Titan",
    category: "astro",
    fact: "Titan is Saturn’s largest moon and is unique for having a dense atmosphere and liquid methane lakes on its surface.",
  },
  {
    id: 156,
    question: "What type of celestial object is Halley's Comet?",
    answer: "A comet",
    category: "astro",
    fact: "Halley's Comet is one of the most famous comets, visible from Earth every 75-76 years. It was last seen in 1986 and will appear again in 2061.",
  },
  {
    id: 157,
    question:
      "What is the name of the spacecraft that first landed humans on the moon?",
    answer: "Apollo 11",
    category: "astro",
    fact: "Apollo 11 was the NASA mission that landed the first humans, Neil Armstrong and Buzz Aldrin, on the Moon in July 1969.",
  },
  {
    id: 158,
    question: "Which planet has the most moons in the solar system?",
    answer: "Jupiter",
    category: "astro",
    fact: "Jupiter has at least 79 moons, the largest of which is Ganymede, bigger than the planet Mercury.",
  },
  {
    id: 159,
    question:
      "What is the name of the space telescope that has provided stunning images of distant galaxies?",
    answer: "Hubble Space Telescope",
    category: "astro",
    fact: "The Hubble Space Telescope has been orbiting Earth since 1990, sending back detailed images of galaxies, nebulae, and other astronomical objects.",
  },
  {
    id: 160,
    question: "What is the name of the first rover to land on Mars?",
    answer: "Sojourner",
    category: "astro",
    fact: "Sojourner was the first Mars rover, part of NASA's Pathfinder mission, and explored the Martian surface in 1997.",
  },
  {
    id: 27,
    question: "What is the largest peninsula in the world?",
    answer: "The Arabian Peninsula",
    category: "geo",
    fact: "The Arabian Peninsula covers about 3.2 million square kilometers (1.25 million square miles), making it the largest peninsula on Earth.",
  },
  {
    id: 28,
    question: "What is the only continent without an active volcano?",
    answer: "Australia",
    category: "geo",
    fact: "Australia is the only continent where there are no active volcanoes.",
  },
  {
    id: 29,
    question:
      "Which river forms the boundary between Mexico and the United States?",
    answer: "The Rio Grande",
    category: "geo",
    fact: "The Rio Grande stretches over 3,000 km (1,900 miles) and serves as a natural boundary between the U.S. and Mexico.",
  },
  {
    id: 30,
    question: "Which city is known as the City of Canals?",
    answer: "Venice",
    category: "geo",
    fact: "Venice, Italy, is famous for its intricate canal system, with over 150 canals running through the city.",
  },
  {
    id: 81,
    question: "Who holds the NFL record for the most career touchdown passes?",
    answer: "Tom Brady",
    category: "sports",
    fact: "Tom Brady holds the NFL record for the most career touchdown passes, with over 600, solidifying his status as one of the greatest quarterbacks of all time.",
  },
  {
    id: 82,
    question: "Which country has won the most Cricket World Cups?",
    answer: "Australia",
    category: "sports",
    fact: "Australia has won the ICC Cricket World Cup five times, the most by any team, with victories in 1987, 1999, 2003, 2007, and 2015.",
  },
  {
    id: 83,
    question: "Which athlete has won the most Tour de France titles?",
    answer:
      "Jacques Anquetil, Eddy Merckx, Bernard Hinault, and Miguel Indurain",
    category: "sports",
    fact: "Each of these cyclists has won the Tour de France five times, making them the most successful riders in the history of the race.",
  },
  {
    id: 84,
    question:
      "Who holds the record for the most goals scored in a calendar year in football?",
    answer: "Lionel Messi",
    category: "sports",
    fact: "Lionel Messi scored 91 goals in 2012, breaking Gerd Müller's 40-year-old record of 85 goals in a calendar year.",
  },
  {
    id: 85,
    question: "Which team won the first ever FIFA World Cup?",
    answer: "Uruguay",
    category: "sports",
    fact: "Uruguay won the first ever FIFA World Cup in 1930, defeating Argentina 4-2 in the final, hosted in Montevideo, Uruguay.",
  },
  {
    id: 86,
    question:
      "Which American football team has the most consecutive Super Bowl appearances?",
    answer: "Buffalo Bills",
    category: "sports",
    fact: "The Buffalo Bills appeared in four consecutive Super Bowls from 1991 to 1994, but unfortunately, they lost all four games.",
  },
  {
    id: 87,
    question: "Who is the youngest player to win a Grand Slam title in tennis?",
    answer: "Martina Hingis",
    category: "sports",
    fact: "Martina Hingis won her first Grand Slam title at the age of 16, becoming the youngest Grand Slam champion in the Open Era.",
  },
  {
    id: 88,
    question: "Which team has won the most Stanley Cups in NHL history?",
    answer: "Montreal Canadiens",
    category: "sports",
    fact: "The Montreal Canadiens have won the Stanley Cup 24 times, the most in NHL history, with their last win in 1993.",
  },
  {
    id: 89,
    question:
      "Which country has won the most gold medals in Olympic basketball?",
    answer: "United States",
    category: "sports",
    fact: "The United States has won 16 gold medals in Olympic basketball, the most of any country, with their first win in 1936.",
  },

  {
    id: 96,
    question: "Who wrote the novel '1984'?",
    answer: "George Orwell",
    category: "arts",
    fact: "'1984' is a dystopian novel published in 1949, depicting a totalitarian regime that uses surveillance and control over its citizens.",
  },
  {
    id: 97,
    question: "Which artist painted the 'Mona Lisa'?",
    answer: "Leonardo da Vinci",
    category: "arts",
    fact: "The 'Mona Lisa' is one of the most famous paintings in the world and is housed in the Louvre Museum in Paris.",
  },
  {
    id: 98,
    question: "Who is the author of 'Pride and Prejudice'?",
    answer: "Jane Austen",
    category: "arts",
    fact: "'Pride and Prejudice', first published in 1813, is one of the most beloved novels in English literature, focusing on themes of class, marriage, and morality.",
  },
  {
    id: 99,
    question: "Which poet wrote 'The Raven'?",
    answer: "Edgar Allan Poe",
    category: "arts",
    fact: "'The Raven' is a narrative poem first published in 1845, and is one of Edgar Allan Poe's most famous works, known for its dark and gothic tone.",
  },
  {
    id: 100,
    question:
      "Which playwright is known for works like 'Hamlet', 'Romeo and Juliet', and 'Macbeth'?",
    answer: "William Shakespeare",
    category: "arts",
    fact: "William Shakespeare is often referred to as England’s national poet and is considered one of the greatest writers in the English language.",
  },

  {
    id: 35,
    question:
      "Who was the first African-American president of the United States?",
    answer: "Barack Obama",
    category: "people",
    fact: "Barack Obama served as the 44th President of the United States from 2009 to 2017, becoming the first African-American to hold the office.",
  },
  {
    id: 126,
    question: "Which famous British band was nicknamed 'The Fab Four'?",
    answer: "The Beatles",
    category: "music",
    fact: "The Beatles, composed of John Lennon, Paul McCartney, George Harrison, and Ringo Starr, are widely regarded as the most influential band in music history.",
  },
  {
    id: 127,
    question: "Who is known for the hit song 'Bohemian Rhapsody'?",
    answer: "Queen",
    category: "music",
    fact: "'Bohemian Rhapsody' was released in 1975 and became one of Queen's most famous songs, known for its unique structure and operatic elements.",
  },
  {
    id: 128,
    question: "Who is the composer of 'The Four Seasons'?",
    answer: "Antonio Vivaldi",
    category: "music",
    fact: "'The Four Seasons' is a set of violin concertos by Vivaldi, written in 1725 and known for their vivid depiction of each season of the year.",
  },
  {
    id: 129,
    question: "Which artist is known for songs like 'Purple Rain' and 'Kiss'?",
    answer: "Prince",
    category: "music",
    fact: "Prince was an innovative musician known for blending genres like funk, rock, and pop, and he became a cultural icon with songs like 'Purple Rain'.",
  },
  {
    id: 130,
    question:
      "Which female artist had a global hit with 'Rolling in the Deep'?",
    answer: "Adele",
    category: "music",
    fact: "'Rolling in the Deep' was released in 2010 and became one of Adele’s signature songs, earning her multiple awards and charting worldwide.",
  },
  {
    id: 131,
    question: "Who is the composer of the opera 'Carmen'?",
    answer: "Georges Bizet",
    category: "music",
    fact: "'Carmen' is one of the most performed operas worldwide, known for its unforgettable music, including the famous 'Habanera' aria.",
  },
  {
    id: 132,
    question: "Which artist is known for the album 'Thriller'?",
    answer: "Michael Jackson",
    category: "music",
    fact: "Released in 1982, 'Thriller' became the best-selling album of all time, featuring iconic songs like 'Beat It' and 'Billie Jean.'",
  },
  {
    id: 133,
    question: "Who is the lead vocalist of the rock band Led Zeppelin?",
    answer: "Robert Plant",
    category: "music",
    fact: "Robert Plant's powerful vocals helped define Led Zeppelin's sound, making the band one of the most successful rock groups in history.",
  },
  {
    id: 134,
    question: "Which classical composer became deaf later in life?",
    answer: "Ludwig van Beethoven",
    category: "music",
    fact: "Despite losing his hearing, Beethoven continued to compose some of his greatest works, including his Ninth Symphony.",
  },
  {
    id: 135,
    question: "Who is known for the songs 'Rocket Man' and 'Your Song'?",
    answer: "Elton John",
    category: "music",
    fact: "Elton John is one of the best-selling music artists in the world, known for his piano-driven pop songs and his flamboyant stage presence.",
  },
  {
    id: 136,
    question:
      "Which jazz musician is famous for playing the trumpet and for songs like 'What a Wonderful World'?",
    answer: "Louis Armstrong",
    category: "music",
    fact: "Louis Armstrong, also known as 'Satchmo,' was a pioneering figure in jazz, and his gravelly voice and trumpet playing made him an international star.",
  },
  {
    id: 137,
    question:
      "Which singer-songwriter is known for albums like 'Blue' and 'Court and Spark'?",
    answer: "Joni Mitchell",
    category: "music",
    fact: "Joni Mitchell is a highly influential folk and rock singer-songwriter, known for her poetic lyrics and innovative use of open guitar tunings.",
  },
  {
    id: 138,
    question: "Which composer wrote the ballet 'The Nutcracker'?",
    answer: "Pyotr Ilyich Tchaikovsky",
    category: "music",
    fact: "'The Nutcracker' premiered in 1892 and has since become one of the most beloved ballets, particularly associated with the holiday season.",
  },
  {
    id: 139,
    question: "Which band is known for the hit song 'Stairway to Heaven'?",
    answer: "Led Zeppelin",
    category: "music",
    fact: "'Stairway to Heaven' is one of the most famous rock songs ever, and it has become synonymous with Led Zeppelin’s legendary status in rock history.",
  },
  {
    id: 140,
    question: "Which artist released the iconic album 'Like a Virgin'?",
    answer: "Madonna",
    category: "music",
    fact: "'Like a Virgin,' released in 1984, was a breakthrough album for Madonna, solidifying her as a pop icon and paving the way for her future success.",
  },
  {
    id: 45,
    question: "Who invented the television?",
    answer: "Philo Farnsworth",
    category: "people",
    fact: "Philo Farnsworth was the first person to create a fully electronic television system in 1927, revolutionizing entertainment and communication.",
  },

  {
    id: 65,
    question:
      "Which country has won the most medals in the history of the Summer Olympics?",
    answer: "The United States",
    category: "sports",
    fact: "The United States has won more than 2,500 medals in the Summer Olympics, more than any other country in the competition's history.",
  },

  {
    id: 66,
    question: "Who is the all-time top scorer in the NBA?",
    answer: "LeBron James",
    category: "sports",
    fact: "LeBron James became the all-time leading scorer in NBA history in 2023, surpassing Kareem Abdul-Jabbar’s previous record.",
  },
  {
    id: 67,
    question: "Which country has won the most Rugby World Cups?",
    answer: "New Zealand",
    category: "sports",
    fact: "The New Zealand All Blacks have won the Rugby World Cup three times, in 1987, 2011, and 2015, making them one of the most dominant teams in rugby history.",
  },
  {
    id: 68,
    question: "Who has won the most Olympic gold medals in history?",
    answer: "Michael Phelps",
    category: "sports",
    fact: "Michael Phelps has won 23 Olympic gold medals, the most of any athlete, with his total medal count reaching 28.",
  },
  {
    id: 69,
    question:
      "Which tennis player has held the number one ATP ranking for the longest time?",
    answer: "Novak Djokovic",
    category: "sports",
    fact: "Novak Djokovic holds the record for the most weeks as world number one in the ATP rankings, surpassing Roger Federer’s previous record.",
  },
  {
    id: 70,
    question:
      "Who is the only boxer to win world titles in eight different weight classes?",
    answer: "Manny Pacquiao",
    category: "sports",
    fact: "Manny Pacquiao, a Filipino boxing legend, is the only boxer in history to win world titles in eight different weight divisions.",
  },
  {
    id: 71,
    question: "Which country hosted the first modern Olympic Games?",
    answer: "Greece",
    category: "sports",
    fact: "The first modern Olympic Games were held in Athens, Greece, in 1896, reviving the ancient Greek tradition.",
  },
  {
    id: 72,
    question:
      "Who was the first woman to win six Olympic gold medals in track and field?",
    answer: "Allyson Felix",
    category: "sports",
    fact: "Allyson Felix became the first woman to win six Olympic gold medals in track and field, earning a total of 11 Olympic medals in her career.",
  },
  {
    id: 73,
    question: "Which soccer player has won the most Ballon d'Or awards?",
    answer: "Lionel Messi",
    category: "sports",
    fact: "As of 2023, Lionel Messi has won the prestigious Ballon d'Or award 8 times, the most in football history.",
  },

  {
    id: 74,
    question:
      "Who was the first cricketer to score 100 international centuries?",
    answer: "Sachin Tendulkar",
    category: "sports",
    fact: "Sachin Tendulkar, an Indian cricket legend, became the first cricketer to score 100 international centuries, a record that remains unbeaten.",
  },
  {
    id: 75,
    question: "Which team has won the most Super Bowl titles?",
    answer: "Pittsburgh Steelers and New England Patriots",
    category: "sports",
    fact: "As of 2023, both the Pittsburgh Steelers and the New England Patriots are tied with six Super Bowl titles each, the most in NFL history.",
  },
  {
    id: 76,
    question: "Who is the all-time top goal scorer in FIFA World Cup history?",
    answer: "Miroslav Klose",
    category: "sports",
    fact: "German striker Miroslav Klose holds the record for the most goals in FIFA World Cup history, with 16 goals across four tournaments (2002–2014).",
  },
  {
    id: 77,
    question: "Who is the fastest female sprinter in history?",
    answer: "Florence Griffith-Joyner",
    category: "sports",
    fact: "Florence Griffith-Joyner, also known as Flo-Jo, set the women's 100m and 200m world records in 1988, which still stand today.",
  },
  {
    id: 78,
    question: "Which golfer has won the most Masters titles?",
    answer: "Jack Nicklaus",
    category: "sports",
    fact: "Jack Nicklaus, known as 'The Golden Bear,' has won six Masters titles, the most in the tournament’s history.",
  },

  {
    id: 1011,
    question: "Which artist is known for cutting off part of his own ear?",
    answer: "Vincent van Gogh",
    category: "arts",
    fact: "Vincent van Gogh is a post-impressionist painter known for his expressive use of color and emotional depth, but he struggled with mental illness throughout his life.",
  },
  {
    id: 1022,
    question: "Who painted the ceiling of the Sistine Chapel?",
    answer: "Michelangelo",
    category: "arts",
    fact: "Michelangelo spent four years painting the Sistine Chapel ceiling, a masterpiece of Renaissance art that features scenes from the Book of Genesis.",
  },
  {
    id: 1063,
    question: "What art movement is Pablo Picasso associated with?",
    answer: "Cubism",
    category: "arts",
    fact: "Pablo Picasso co-founded Cubism, an art movement that broke objects down into geometric shapes, changing the perspective on how art could represent reality.",
  },
  {
    id: 1047,
    question: "Which artist is famous for the painting 'The Starry Night'?",
    answer: "Vincent van Gogh",
    category: "arts",
    fact: "'The Starry Night' was painted in 1889 while Van Gogh was in a mental asylum in Saint-Rémy-de-Provence, and it depicts a swirling night sky over a small town.",
  },
  {
    id: 1056,
    question: "Who sculpted 'David'?",
    answer: "Michelangelo",
    category: "arts",
    fact: "Michelangelo's 'David' is one of the most iconic sculptures of the Renaissance, showcasing the biblical hero at the moment before his battle with Goliath.",
  },
  {
    id: 79,
    question:
      "Which soccer club has won the most UEFA Champions League titles?",
    answer: "Real Madrid",
    category: "sports",
    fact: "Real Madrid has won the UEFA Champions League a record 14 times, making them the most successful club in European football.",
  },
  {
    id: 80,
    question:
      "Who was the first female gymnast to score a perfect 10 at the Olympics?",
    answer: "Nadia Comăneci",
    category: "sports",
    fact: "Nadia Comăneci made history at the 1976 Montreal Olympics by becoming the first gymnast to score a perfect 10, at the age of just 14.",
  },

  {
    id: 90,
    question:
      "Who holds the record for the most home runs in Major League Baseball?",
    answer: "Barry Bonds",
    category: "sports",
    fact: "Barry Bonds holds the all-time record for home runs in MLB, with 762 home runs over his career, breaking Hank Aaron's long-standing record.",
  },
  {
    id: 46,
    question: "Who invented dynamite?",
    answer: "Alfred Nobel",
    category: "people",
    fact: "Alfred Nobel invented dynamite in 1867. He later established the Nobel Prizes, including the Nobel Peace Prize, which is awarded to individuals and groups for outstanding contributions to peace.",
  },
  {
    id: 47,
    question: "Who is credited with inventing the first personal computer?",
    answer: "Steve Wozniak",
    category: "people",
    fact: "Steve Wozniak co-founded Apple and is credited with inventing the Apple I in 1976, one of the first personal computers designed for home use.",
  },
  {
    id: 53,
    question: "Who invented the steam engine?",
    answer: "James Watt",
    category: "people",
    fact: "James Watt didn’t invent the steam engine but significantly improved it in 1765, making it more efficient and practical for use in industry.",
  },
  {
    id: 54,
    question: "Who invented the sewing machine?",
    answer: "Elias Howe",
    category: "people",
    fact: "Elias Howe received a patent for the first practical sewing machine in 1846, though Isaac Singer later improved the design and popularized it.",
  },
  {
    id: 55,
    question: "Who invented penicillin?",
    answer: "Alexander Fleming",
    category: "people",
    fact: "In 1928, Alexander Fleming discovered penicillin, the world’s first antibiotic, which revolutionized medicine and saved countless lives.",
  },

  {
    id: 31,
    question: "Who was the first person to set foot on the moon?",
    answer: "Neil Armstrong",
    category: "people",
    fact: "Neil Armstrong landed on the moon on July 20, 1969, during NASA's Apollo 11 mission, famously saying, 'That's one small step for man, one giant leap for mankind.'",
  },
  {
    id: 32,
    question: "Who is known as the father of modern physics?",
    answer: "Albert Einstein",
    category: "people",
    fact: "Albert Einstein developed the theory of relativity, one of the two pillars of modern physics, and received the Nobel Prize in Physics in 1921 for his work on the photoelectric effect.",
  },
  {
    id: 33,
    question: "Who was the first female prime minister of the United Kingdom?",
    answer: "Margaret Thatcher",
    category: "people",
    fact: "Margaret Thatcher served as the UK's Prime Minister from 1979 to 1990, making her the longest-serving British prime minister of the 20th century.",
  },
  {
    id: 34,
    question: "Who is known as the 'Mahatma' or Great Soul of India?",
    answer: "Mahatma Gandhi",
    category: "people",
    fact: "Mahatma Gandhi led India to independence from British rule using nonviolent resistance and civil disobedience, influencing movements for civil rights and freedom across the world.",
  },

  {
    id: 61,
    question: "Which country has won the most FIFA World Cup titles?",
    answer: "Brazil",
    category: "sports",
    fact: "Brazil has won the FIFA World Cup five times: in 1958, 1962, 1970, 1994, and 2002, making them the most successful team in the tournament's history.",
  },
  {
    id: 62,
    question:
      "Who holds the record for the most Grand Slam tennis titles in men's singles?",
    answer: "Novak Djokovic",
    category: "sports",
    fact: "As of 2023, Novak Djokovic has won 24 Grand Slam titles, surpassing previous record holders in men’s singles.",
  },
  {
    id: 63,
    question: "Which Olympic Games had the first appearance of women's boxing?",
    answer: "London 2012",
    category: "sports",
    fact: "Women’s boxing made its Olympic debut at the London 2012 Summer Olympics, where Nicola Adams of Great Britain won the first gold medal.",
  },
  {
    id: 64,
    question: "Who is considered the fastest man in the world?",
    answer: "Usain Bolt",
    category: "sports",
    fact: "Usain Bolt holds the world record for the 100 meters at 9.58 seconds, set in 2009, and is an eight-time Olympic gold medalist.",
  },

  {
    id: 36,
    question: "Who invented the telephone?",
    answer: "Alexander Graham Bell",
    category: "people",
    fact: "Alexander Graham Bell was awarded the first US patent for the invention of the telephone in 1876. His mother and wife were both deaf, influencing his work in communication.",
  },
  {
    id: 37,
    question: "Who invented the light bulb?",
    answer: "Thomas Edison",
    category: "people",
    fact: "Thomas Edison didn’t invent the first light bulb but improved it enough to create the first commercially viable incandescent bulb, patented in 1879.",
  },
  {
    id: 38,
    question: "Who invented the airplane?",
    answer: "The Wright Brothers",
    category: "people",
    fact: "Orville and Wilbur Wright made the first powered flight on December 17, 1903, in Kitty Hawk, North Carolina, revolutionizing transportation.",
  },
  {
    id: 39,
    question: "Who invented the World Wide Web?",
    answer: "Tim Berners-Lee",
    category: "people",
    fact: "Tim Berners-Lee, a British computer scientist, invented the World Wide Web in 1989 while working at CERN. He also created the first web browser and website.",
  },
  {
    id: 40,
    question: "Who invented the printing press?",
    answer: "Johannes Gutenberg",
    category: "people",
    fact: "Johannes Gutenberg’s invention of the movable-type printing press in the 1440s led to the mass production of books, revolutionizing communication and education.",
  },
  {
    id: 41,
    question: "Who developed the first successful polio vaccine?",
    answer: "Jonas Salk",
    category: "people",
    fact: "Jonas Salk developed the first effective polio vaccine in 1955, significantly reducing the number of polio cases worldwide.",
  },

  {
    id: 48,
    question: "Who invented the electric battery?",
    answer: "Alessandro Volta",
    category: "people",
    fact: "Alessandro Volta, an Italian physicist, invented the electric battery in 1800, creating the first steady source of electric current.",
  },
  {
    id: 49,
    question: "Who is known as the 'father of modern aviation'?",
    answer: "George Cayley",
    category: "people",
    fact: "George Cayley, an English engineer, is credited with laying the foundation of modern aviation, identifying the forces of flight: lift, drag, thrust, and weight, as early as 1799.",
  },
  {
    id: 50,
    question: "Who invented the microwave oven?",
    answer: "Percy Spencer",
    category: "people",
    fact: "Percy Spencer accidentally discovered microwave cooking while working with radar technology in 1945, leading to the invention of the microwave oven.",
  },
  {
    id: 51,
    question: "Who was the first woman to win a Nobel Prize?",
    answer: "Marie Curie",
    category: "people",
    fact: "Marie Curie won the Nobel Prize in Physics in 1903 and later won another in Chemistry in 1911 for her groundbreaking research on radioactivity.",
  },
  {
    id: 161,
    question: "What is the most distant man-made object from Earth?",
    answer: "Voyager 1",
    category: "astro",
    fact: "Launched in 1977, Voyager 1 is now more than 14 billion miles from Earth and continues to send data as it travels through interstellar space.",
  },
  {
    id: 162,
    question:
      "What is the name of the first artificial satellite launched by the United States?",
    answer: "Explorer 1",
    category: "astro",
    fact: "Explorer 1 was launched in 1958 and discovered the Van Allen radiation belts surrounding Earth.",
  },
  {
    id: 163,
    question:
      "Which planet rotates on its side, with its poles facing the Sun?",
    answer: "Uranus",
    category: "astro",
    fact: "Uranus is unique in the solar system because it rotates on its side, possibly due to a collision with an Earth-sized object long ago.",
  },
  {
    id: 164,
    question:
      "What is the term for the boundary around a black hole beyond which no light can escape?",
    answer: "Event Horizon",
    category: "astro",
    fact: "The event horizon is the point of no return for objects falling into a black hole; once crossed, not even light can escape the gravitational pull.",
  },
  {
    id: 165,
    question:
      "What is the name of the dwarf planet located in the asteroid belt?",
    answer: "Ceres",
    category: "astro",
    fact: "Ceres is the largest object in the asteroid belt and was the first dwarf planet to be visited by a spacecraft, NASA’s Dawn mission.",
  },
  {
    id: 166,
    question:
      "What is the name of the region in space where most comets originate?",
    answer: "Oort Cloud",
    category: "astro",
    fact: "The Oort Cloud is a distant, spherical shell of icy objects that is believed to be the source of long-period comets.",
  },
  {
    id: 167,
    question:
      "What is the name of the space agency responsible for Mars missions like Perseverance and Curiosity?",
    answer: "NASA",
    category: "astro",
    fact: "NASA (National Aeronautics and Space Administration) is responsible for many space missions, including the Mars rovers that explore the Red Planet.",
  },
  {
    id: 168,
    question:
      "Which moon of Jupiter is believed to have a vast ocean beneath its icy surface?",
    answer: "Europa",
    category: "astro",
    fact: "Europa is one of Jupiter’s moons and is thought to have a subsurface ocean that may harbor the conditions necessary for life.",
  },
  {
    id: 169,
    question: "Which planet has a day that is longer than its year?",
    answer: "Venus",
    category: "astro",
    fact: "Venus has an extremely slow rotation, so a single day on Venus (one full rotation) is longer than its orbit around the Sun, which takes 225 Earth days.",
  },
  {
    id: 170,
    question:
      "What is the name of the space mission that first landed a probe on a comet?",
    answer: "Rosetta",
    category: "astro",
    fact: "The European Space Agency’s Rosetta mission successfully landed the Philae probe on Comet 67P/Churyumov–Gerasimenko in 2014.",
  },
  {
    id: 52,
    question: "Who developed the theory of evolution?",
    answer: "Charles Darwin",
    category: "people",
    fact: "Charles Darwin introduced the theory of natural selection in his 1859 book 'On the Origin of Species,' fundamentally changing our understanding of biology.",
  },
  {
    id: 42,
    question: "Who is considered the father of modern computers?",
    answer: "Alan Turing",
    category: "people",
    fact: "Alan Turing’s work in the development of algorithms and computing machines laid the foundation for modern computer science, and his work during World War II helped crack the Nazi Enigma code.",
  },
  {
    id: 43,
    question: "Who invented the first automobile?",
    answer: "Karl Benz",
    category: "people",
    fact: "Karl Benz built the first automobile powered by an internal combustion engine in 1885, receiving a patent for it in 1886, marking the beginning of the automotive industry.",
  },
  {
    id: 44,
    question: "Who invented the first programmable computer?",
    answer: "Charles Babbage",
    category: "people",
    fact: "Charles Babbage designed the first mechanical computer, known as the Analytical Engine, in the 1830s, earning him the title of the 'father of the computer.'",
  },
];

export default questions;
